Alter table L_PRODUCT
ADD  
PRODUCT_GRP_DESC nvarchar(30),
PRODUCT_GRP_DESC_SCH nvarchar(30),
PRODUCT_GRP_DESC_TCH nvarchar(30);

Update L_PRODUCT 
SET 
PRODUCT_GRP_DESC = L_PRODUCT_GRP.PRODUCT_GRP_DESC,
PRODUCT_DESC_SCH = L_PRODUCT_GRP.PRODUCT_GRP_DESC_SCH,
PRODUCT_DESC_TCH = L_PRODUCT_GRP.PRODUCT_GRP_DESC_TCH
FROM 
L_PRODUCT 
Inner Join
 L_PRODUCT_GRP
ON
L_PRODUCT.PRODUCT_GRP_ID =  L_PRODUCT_GRP.PRODUCT_GRP_ID

Alter table L_PRODUCT 
Drop Column  PRODUCT_GRP_ID

Delete from L_PRODUCT_GRP

Drop Table L_PRODUCT_GRP

Alter Table L_CUSTOMER
ADD  
CUST_LV_SCORE_DESC nvarchar(30),
CUST_LV_SCORE_DESC_SCH nvarchar(30),
CUST_LV_SCORE_DESC_TCH nvarchar(30),
CUST_HOUSING_DESC nvarchar(30),
CUST_HOUSING_DESC_SCH nvarchar(30), 
CUST_HOUSING_DESC_TCH nvarchar(30),
CUST_EDUCATION_DESC nvarchar(30),
CUST_EDUCATION_DESC_SCH nvarchar(30),
CUST_EDUCATION_DESC_TCH nvarchar(30),
MARITAL_STS_DESC nvarchar(30),
MARITAL_STS_DESC_SCH nvarchar(30),
MARITAL_STS_DESC_TCH nvarchar(30),
CUST_HH_COUNT_DESC nvarchar(30),
CUST_GENDER_DESC nvarchar(30),
CUST_GENDER_DESC_SCH nvarchar(30),
CUST_GENDER_DESC_TCH nvarchar(30),
CUST_AGE_RNG_DESC nvarchar(30),
CUST_INC_RNG_DESC nvarchar(30),
CUST_STATUS_DESC nvarchar(30),
CUST_STATUS_DESC_SCH nvarchar(30),
CUST_STATUS_DESC_TCH nvarchar(30),
CUST_CITY_DESC nvarchar(30),
CUST_REGION_DESC nvarchar(30),
CUST_REGION_DESC_SCH nvarchar(30),
CUST_REGION_DESC_TCH nvarchar(30),
CUST_STATE_DESC nvarchar(30)

Update L_CUSTOMER 
SET 
CUST_LV_SCORE_DESC = Score.CUST_LV_SCORE_DESC,
CUST_LV_SCORE_DESC_SCH = Score.CUST_LV_SCORE_DESC_SCH,
CUST_LV_SCORE_DESC_TCH = Score.CUST_LV_SCORE_DESC_TCH,
CUST_HOUSING_DESC = Housing.CUST_HOUSING_DESC,
CUST_HOUSING_DESC_SCH = Housing.CUST_HOUSING_DESC_SCH,
CUST_HOUSING_DESC_TCH = Housing.CUST_HOUSING_DESC_TCH,
CUST_EDUCATION_DESC = Edu.CUST_EDUCATION_DESC,
CUST_EDUCATION_DESC_SCH = Edu.CUST_EDUCATION_DESC_SCH,
CUST_EDUCATION_DESC_TCH = Edu.CUST_EDUCATION_DESC_TCH,
MARITAL_STS_DESC = MS.MARITAL_STS_DESC,
MARITAL_STS_DESC_SCH = MS.MARITAL_STS_DESC_SCH,
MARITAL_STS_DESC_TCH = MS.MARITAL_STS_DESC_TCH,
CUST_HH_COUNT_DESC = HHCount.CUST_HH_COUNT_DESC,
CUST_GENDER_DESC = Gender.CUST_GENDER_DESC,
CUST_GENDER_DESC_SCH = Gender.CUST_GENDER_DESC_SCH,
CUST_GENDER_DESC_TCH = Gender.CUST_GENDER_DESC_TCH,
CUST_AGE_RNG_DESC = Age.CUST_AGE_RNG_DESC,
CUST_INC_RNG_DESC =  Income.CUST_INC_RNG_DESC,
CUST_STATUS_DESC = CStatus.CUST_STATUS_DESC,
CUST_STATUS_DESC_SCH = CStatus.CUST_STATUS_DESC_SCH,
CUST_STATUS_DESC_TCH = CStatus.CUST_STATUS_DESC_TCH,
CUST_CITY_DESC = City.CUST_CITY_DESC,
CUST_REGION_DESC = City.CUST_REGION_DESC,
CUST_REGION_DESC_SCH = City.CUST_REGION_DESC_SCH,
CUST_REGION_DESC_TCH = City.CUST_REGION_DESC_TCH,
CUST_STATE_DESC = City.CUST_STATE_DESC

FROM 
L_CUSTOMER AS Cust
Join L_CUST_LV_SCORE AS Score
	ON
	Cust.CUST_LV_SCORE_ID = Score.CUST_LV_SCORE_ID
Join L_CUST_HOUSING As Housing
	ON 
	Cust.CUST_HOUSING_ID = Housing.CUST_HOUSING_ID
Join L_CUST_EDUCATION as Edu
	ON
	Cust.CUST_EDUCATION_ID = Edu.CUST_EDUCATION_ID
Join L_CUST_MARITAL_STS as MS
	ON
	Cust.MARITAL_STS_ID = MS.MARITAL_STS_ID
Join L_CUST_HH_COUNT as HHCount
	ON
	Cust.CUST_HH_COUNT_ID = HHCount.CUST_HH_COUNT_ID
Join L_CUST_GENDER As Gender
	ON
	Cust.CUST_GENDER_ID = Gender.CUST_GENDER_ID
Join L_CUST_AGE_RNG as Age
	ON
	Cust.CUST_AGE_RNG_ID = Age.CUST_AGE_RNG_ID
Join L_CUST_INC_RNG AS Income
	ON
	Cust.CUST_INC_RNG_ID = Income.CUST_INC_RNG_ID
Join L_CUST_STATUS as CStatus
	ON
	Cust.CURR_CUST_STATUS_ID = CStatus.CUST_STATUS_ID
Join L_CUST_CITY as City
	ON
	Cust.CUST_CITY_ID = City.CUST_CITY_ID

ALTER Table L_CUSTOMER
DROP COLUMN CUST_LV_SCORE_ID,
CUST_CITY_ID,
CURR_CUST_STATUS_ID,
CUST_INC_RNG_ID,
CUST_AGE_RNG_ID,
CUST_GENDER_ID,
CUST_HH_COUNT_ID,
MARITAL_STS_ID,
CUST_EDUCATION_ID,
CUST_HOUSING_ID;

Delete from L_CUST_LV_SCORE
Delete from L_CUST_HOUSING
Delete from L_CUST_EDUCATION
Delete from L_CUST_MARITAL_STS
Delete from L_CUST_HH_COUNT
Delete from L_CUST_GENDER
Delete from L_CUST_AGE_RNG
Delete from L_CUST_INC_RNG
Delete from L_CUST_STATUS
Delete from L_CUST_CITY

DROP TABLE L_CUST_LV_SCORE
DROP TABLE L_CUST_HOUSING
DROP TABLE L_CUST_EDUCATION
DROP TABLE L_CUST_MARITAL_STS
DROP TABLE L_CUST_HH_COUNT
DROP TABLE L_CUST_GENDER
DROP TABLE L_CUST_AGE_RNG
DROP TABLE L_CUST_INC_RNG
DROP TABLE L_CUST_STATUS
DROP TABLE L_CUST_CITY


Alter Table L_CAL_DATE
ADD  
MNTH_DESC nvarchar(30),
MNTH_DESC_SCH nvarchar(30),
MNTH_DESC_TCH nvarchar(30),
QTR_DESC nvarchar(30),
QTR_DESC_SCH nvarchar(30),
QTR_DESC_TCH nvarchar(30),
LAST_YEAR_ID float;

Update L_CAL_DATE 
SET 
MNTH_DESC = CMonth.MNTH_DESC,
MNTH_DESC_SCH = CMonth.MNTH_DESC_SCH,
MNTH_DESC_TCH = CMonth.MNTH_DESC_TCH,
QTR_DESC = CQtr.QTR_DESC,
QTR_DESC_SCH = CQtr.QTR_DESC_SCH,
QTR_DESC_TCH = CQtr.QTR_DESC_TCH,
LAST_YEAR_ID = CYr.LAST_YEAR_ID
FROM 
L_CAL_DATE AS CDate
Join L_CAL_MNTH AS CMonth
	ON
	CDate.MNTH_ID = CMonth.MNTH_ID
Join L_CAL_QTR As CQtr
	ON 
	CDate.QTR_ID = CQtr.QTR_ID
Join L_CAL_YEAR As CYr
	ON
	CDate.YEAR_ID = CYr.YEAR_ID
	

ALTER Table L_CAL_DATE
DROP COLUMN MNTH_ID,
QTR_ID;

Delete from L_CAL_MNTH
Delete from L_CAL_QTR
Delete from L_CAL_YEAR

Drop Table L_CAL_MNTH
Drop Table L_CAL_QTR
Drop Table L_CAL_YEAR


